// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wfrp.Infrastructure.Data;

#nullable disable

namespace Wfrp.Infrastructure.Migrations
{
    [DbContext(typeof(WfrpDbContext))]
    [Migration("20250519114204_UpdateTalents")]
    partial class UpdateTalents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wfrp.Domain.Entities.Career", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareerClassId");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CareerClasses");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CanAdvanceCharacteristics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CareerId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("StatusLevel")
                        .HasColumnType("integer");

                    b.Property<int>("StatusTier")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareerId");

                    b.ToTable("CareerLevels");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevelSkill", b =>
                {
                    b.Property<int>("CareerLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("CareerLevelId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CareerLevelSkill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevelTalent", b =>
                {
                    b.Property<int>("CareerLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("TalentId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.HasKey("CareerLevelId", "TalentId");

                    b.HasIndex("TalentId");

                    b.ToTable("CareerLevelTalent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CareerLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentCareerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperienceSpent")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceTotal")
                        .HasColumnType("integer");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FatePoints")
                        .HasColumnType("integer");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LongTermAmbition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Psychology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("ResiliencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("ShortTermAmbition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCareerId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterCareer", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CareerId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "CareerId");

                    b.HasIndex("CareerId");

                    b.ToTable("CharacterCareer");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItem");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("AcquiredAtLevel")
                        .HasColumnType("integer");

                    b.Property<int>("XPSpent")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterTalent", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("TalentId")
                        .HasColumnType("integer");

                    b.Property<int>("AcquiredAtLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "TalentId");

                    b.HasIndex("TalentId");

                    b.ToTable("CharacterTalent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Flaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Flaws");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.ItemFlaw", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("FlawId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId", "FlawId");

                    b.HasIndex("FlawId");

                    b.ToTable("ItemFlaws");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.ItemQuality", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QualityId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId", "QualityId");

                    b.HasIndex("QualityId");

                    b.ToTable("ItemQualities");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExtraPoints")
                        .HasColumnType("integer");

                    b.Property<int>("FatePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Movement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResiliencePoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.RaceSkill", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("InitialLevel")
                        .HasColumnType("integer");

                    b.HasKey("RaceId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("RaceSkill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.RaceTalent", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("TalentId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.HasKey("RaceId", "TalentId");

                    b.HasIndex("TalentId");

                    b.ToTable("RaceTalent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Characteristic")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdvanced")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGrouped")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeRanked")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MaximumLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("Wfrp.Shared.Enums.Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualities");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Armor", b =>
                {
                    b.HasBaseType("Wfrp.Domain.Entities.Item");

                    b.Property<int>("ArmorPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Gear", b =>
                {
                    b.HasBaseType("Wfrp.Domain.Entities.Item");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Gear");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Weapon", b =>
                {
                    b.HasBaseType("Wfrp.Domain.Entities.Item");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reach")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Career", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.CareerClass", "CareerClass")
                        .WithMany("Careers")
                        .HasForeignKey("CareerClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerClass");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevel", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Career", "Career")
                        .WithMany("Levels")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevelSkill", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.CareerLevel", "CareerLevel")
                        .WithMany("Skills")
                        .HasForeignKey("CareerLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerLevel");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevelTalent", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.CareerLevel", "CareerLevel")
                        .WithMany("Talents")
                        .HasForeignKey("CareerLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerLevel");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Character", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Career", "CurrentCareer")
                        .WithMany()
                        .HasForeignKey("CurrentCareerId");

                    b.HasOne("Wfrp.Domain.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wfrp.Domain.Entities.Characteristics", "AdvancesCharacteristics", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("Agility")
                                .HasColumnType("integer");

                            b1.Property<int>("BallisticSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer");

                            b1.Property<int>("Fellowship")
                                .HasColumnType("integer");

                            b1.Property<int>("Initiative")
                                .HasColumnType("integer");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer");

                            b1.Property<int>("Toughness")
                                .HasColumnType("integer");

                            b1.Property<int>("WeaponSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Willpower")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Wfrp.Domain.Entities.Characteristics", "InitialCharacteristics", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("Agility")
                                .HasColumnType("integer");

                            b1.Property<int>("BallisticSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer");

                            b1.Property<int>("Fellowship")
                                .HasColumnType("integer");

                            b1.Property<int>("Initiative")
                                .HasColumnType("integer");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer");

                            b1.Property<int>("Toughness")
                                .HasColumnType("integer");

                            b1.Property<int>("WeaponSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Willpower")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("AdvancesCharacteristics")
                        .IsRequired();

                    b.Navigation("CurrentCareer");

                    b.Navigation("InitialCharacteristics")
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterCareer", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Career", "Career")
                        .WithMany()
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Character", "Character")
                        .WithMany("CareerHistory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterSkill", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CharacterTalent", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Character", "Character")
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.ItemFlaw", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Flaw", "Flaw")
                        .WithMany()
                        .HasForeignKey("FlawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Item", "Item")
                        .WithMany("Flaws")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flaw");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.ItemQuality", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Item", "Item")
                        .WithMany("Qualities")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Shared.Enums.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Race", b =>
                {
                    b.OwnsOne("Wfrp.Domain.Entities.Characteristics", "BaseCharacteristics", b1 =>
                        {
                            b1.Property<int>("RaceId")
                                .HasColumnType("integer");

                            b1.Property<int>("Agility")
                                .HasColumnType("integer");

                            b1.Property<int>("BallisticSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer");

                            b1.Property<int>("Fellowship")
                                .HasColumnType("integer");

                            b1.Property<int>("Initiative")
                                .HasColumnType("integer");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer");

                            b1.Property<int>("Toughness")
                                .HasColumnType("integer");

                            b1.Property<int>("WeaponSkill")
                                .HasColumnType("integer");

                            b1.Property<int>("Willpower")
                                .HasColumnType("integer");

                            b1.HasKey("RaceId");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceId");
                        });

                    b.Navigation("BaseCharacteristics")
                        .IsRequired();
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.RaceSkill", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Race", "Race")
                        .WithMany("StartingSkills")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.RaceTalent", b =>
                {
                    b.HasOne("Wfrp.Domain.Entities.Race", "Race")
                        .WithMany("StartingTalents")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp.Domain.Entities.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Career", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerClass", b =>
                {
                    b.Navigation("Careers");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.CareerLevel", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Character", b =>
                {
                    b.Navigation("CareerHistory");

                    b.Navigation("Inventory");

                    b.Navigation("Skills");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Item", b =>
                {
                    b.Navigation("Flaws");

                    b.Navigation("Qualities");
                });

            modelBuilder.Entity("Wfrp.Domain.Entities.Race", b =>
                {
                    b.Navigation("StartingSkills");

                    b.Navigation("StartingTalents");
                });
#pragma warning restore 612, 618
        }
    }
}
