apiVersion: v1
kind: Service
metadata:
  name: wfrp-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: wfrp-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfrp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wfrp-api
  template:
    metadata:
      labels:
        app: wfrp-api
    spec:
      containers:
        - name: wfrp-api
          image: wfrp-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Database=wfrpdb;Username=wfrpuser;Password=wfrppassword"
